# Generated by Django 3.2.8 on 2021-10-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_incio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('estado', models.IntegerField(choices=[(1, 'To Do'), (2, 'Doing'), (3, 'Done')], default=1)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.proyecto')),
            ],
            options={
                'verbose_name': 'Sprint',
                'db_table': 'sprint',
                'ordering': ['name'],
            },
        ),
    ]
