# Generated by Django 3.2.6 on 2021-10-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_sprint_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='equipo',
        ),
    ]
