# Generated by Django 3.2.6 on 2021-10-09 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_remove_equipo_sprint'),
        ('sprint', '0003_remove_sprint_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo'),
        ),
    ]
