# Generated by Django 3.2.6 on 2021-10-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0004_sprint_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='equipo',
        ),
    ]
