# Generated by Django 3.2.6 on 2021-10-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0003_miembro_user'),
        ('sprint', '0002_sprint_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.PositiveIntegerField(null=True)),
                ('miembros', models.ManyToManyField(to='miembros.Miembro')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
            ],
        ),
    ]
