# Generated by Django 3.2.6 on 2021-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'db_table': 'equipo',
                'ordering': ['id'],
            },
        ),
    ]
