# Generated by Django 3.2.6 on 2021-10-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0001_initial'),
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='miembros',
            field=models.ManyToManyField(to='miembros.Miembro'),
        ),
    ]
