# Generated by Django 3.2.6 on 2021-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_equipo_miembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
