# Generated by Django 3.2.6 on 2021-10-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_remove_sprint_equipo'),
        ('equipo', '0003_alter_equipo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint'),
        ),
    ]
