# Generated by Django 3.2.6 on 2021-10-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_miembro_user'),
        ('sprint', '0005_remove_sprint_equipo'),
        ('equipo', '0005_remove_equipo_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='miembros',
            field=models.ManyToManyField(blank=True, to='miembros.Miembro'),
        ),
    ]
