# Generated by Django 3.2.6 on 2021-09-03 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolproyecto',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.proyecto'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miembros.rolproyecto'),
        ),
    ]
