# Generated by Django 3.2.6 on 2021-08-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('creator', models.IntegerField(max_length=2, verbose_name='Creador')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, verbose_name='nombres')),
                ('lastname', models.CharField(max_length=50, verbose_name='apellidos')),
                ('ci', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('email', models.CharField(max_length=70, verbose_name='emaill')),
                ('fecha_nac', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
