# Generated by Django 3.2.6 on 2021-08-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proyecto',
            table='proyecto',
        ),
    ]
