# Generated by Django 3.2.6 on 2021-08-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principalApp', '0002_alter_proyecto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='creator',
            field=models.IntegerField(verbose_name='Creador'),
        ),
    ]
