# Generated by Django 3.2.6 on 2021-09-20 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
                ('activo', models.BooleanField(blank=True, default=True, verbose_name='activo/eliminado')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'db_table': 'etiqueta',
                'ordering': ['name'],
            },
        ),
    ]
