# Generated by Django 3.2.6 on 2021-09-20 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etiqueta', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='proyecto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.proyecto', verbose_name='Proyeco al que pertenecet'),
        ),
    ]
