# Generated by Django 3.2.6 on 2021-09-19 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etiqueta', '0002_etiqueta_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_etiqueta_set', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
    ]
