# Generated by Django 3.2.6 on 2021-09-19 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_proyecto_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etiqueta', '0003_etiqueta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='activo',
            field=models.BooleanField(blank=True, default=True, verbose_name='activo/eliminado'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='proyecto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.proyecto', verbose_name='Proyeco al que pertenecet'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_etiqueta_set', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
    ]
