# Generated by Django 3.2.6 on 2021-10-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
            ],
            options={
                'verbose_name': 'SprintPlanning',
                'db_table': 'sprintplanning',
                'ordering': ['sprint'],
            },
        ),
    ]
