# Generated by Django 3.2.6 on 2021-09-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('active', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('E', 'Espera'), ('I', 'Iniciado'), ('P', 'Pausado'), ('C', 'Cancelado')], default='E', max_length=20)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
