# Generated by Django 3.2.6 on 2021-09-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=2000)),
                ('dificultad', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Us',
                'db_table': 'Us',
                'ordering': ['id'],
            },
        ),
    ]
