# Generated by Django 3.2.6 on 2021-09-17 20:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=2000)),
                ('prioridad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('storypoints', models.PositiveIntegerField(null=True)),
                ('estado', models.IntegerField(choices=[(1, 'To Do'), (2, 'Doing'), (3, 'QA'), (4, 'Done')], default=1)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.proyecto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miembros.miembro')),
            ],
            options={
                'verbose_name': 'Us',
                'db_table': 'us',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistorialUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=2000)),
                ('prioridad', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('storypoints', models.PositiveIntegerField()),
                ('fecha_modificacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de modificacion')),
                ('ustory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='us.us')),
            ],
        ),
    ]
