# Generated by Django 3.2.6 on 2021-09-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=2000)),
                ('storyPoint', models.PositiveIntegerField(default=0)),
                ('prioridad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('estado', models.IntegerField(choices=[(1, 'To Do'), (2, 'Doing'), (3, 'QA'), (4, 'Done')], default=1)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.proyecto')),
            ],
            options={
                'verbose_name': 'Us',
                'db_table': 'Us',
                'ordering': ['name'],
            },
        ),
    ]
