# Generated by Django 3.2.6 on 2021-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='us',
            options={'ordering': ['name'], 'verbose_name': 'Us'},
        ),
        migrations.AlterField(
            model_name='us',
            name='dificultad',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='us',
            name='estado',
            field=models.IntegerField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('QA', 'QA'), ('Done', 'Done')], default=1),
        ),
    ]
