# Generated by Django 3.2.6 on 2021-09-17 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_miembro_user'),
        ('us', '0002_us_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='us',
            name='storyPoint',
        ),
        migrations.AddField(
            model_name='us',
            name='storypoints',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='us',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miembros.miembro'),
        ),
        migrations.AlterModelTable(
            name='us',
            table='us',
        ),
        migrations.CreateModel(
            name='HistorialUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=2000)),
                ('prioridad', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('storypoints', models.PositiveIntegerField()),
                ('fecha_modificacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de modificacion')),
                ('ustory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='us.us')),
            ],
        ),
    ]
