# Generated by Django 3.2.6 on 2021-09-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='us',
            options={'ordering': ['prioridad', 'name'], 'permissions': (('add_usproducbacklog', 'Can add Us to Product Backlog'), ('view_usproducbacklog', 'Can view Us to Product Backlog'), ('delete_usproducbacklog', 'Can delete Us to Product Backlog'), ('change_usproducbacklog', 'Can view Us to Product Backlog')), 'verbose_name': 'Us'},
        ),
    ]
