# Generated by Django 3.2.6 on 2021-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_alter_us_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialus',
            name='storypoints',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
