# Generated by Django 3.2.6 on 2021-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_comentarios_historialcomentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcomentarios',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historialcomentarios',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='historialcomentarios',
            name='project',
        ),
        migrations.RemoveField(
            model_name='historialcomentarios',
            name='us',
        ),
        migrations.AddField(
            model_name='historialcomentarios',
            name='creator_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombre de Creador'),
        ),
        migrations.AddField(
            model_name='historialcomentarios',
            name='project_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombre de Proyecto'),
        ),
        migrations.AddField(
            model_name='historialcomentarios',
            name='us_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombre de User Story'),
        ),
        migrations.AlterField(
            model_name='historialcomentarios',
            name='comentarios',
            field=models.CharField(max_length=2000, null=True, unique=True, verbose_name='Contenido del comentario'),
        ),
        migrations.AlterField(
            model_name='historialcomentarios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
