# Generated by Django 3.2.6 on 2021-09-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0004_alter_historialus_storypoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us',
            name='storypoints',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
