# Generated by Django 3.2.6 on 2021-09-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0005_alter_us_storypoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='us',
            options={'ordering': ['prioridad', 'name'], 'permissions': (('add_usproductbacklog', 'Can add Us to Product Backlog'), ('view_usproductbacklog', 'Can view Us to Product Backlog'), ('delete_usproductbacklog', 'Can delete Us to Product Backlog'), ('change_usproductbacklog', 'Can view Us to Product Backlog'), ('valuate_us', 'Can calificate Us to Sprint Backlog')), 'verbose_name': 'Us'},
        ),
    ]
